name: "push an image on merge to master"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

on:
  push:
    branches:
      - master
jobs:
  build-and-push-amd64-k8s-rdma-shared-dev-plugin:
    name: image push amd64
    runs-on: ubuntu-22.04
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push k8s-rdma-shared-dev-plugin
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest-amd64
          file: ./Dockerfile

  push-manifest:
    runs-on: ubuntu-22.04
    needs: [build-and-push-amd64-k8s-rdma-shared-dev-plugin]
    steps:
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create manifest for multi-arch images
      run: |
        docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest -t ${{ env.IMAGE_NAME }}:sha-${{ github.sha }} \
        ${{ env.IMAGE_NAME }}:latest-amd64
